### ISSUE TITLE
Prepare docker container with CS simulator and Kafka

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-simulator-kafka#1]
1) Create develop branch 
2) Create feature branch from develop
3) Prepare docker container with CS simulator and Kafka
4) Add step to the jobs (with triggers) to create a container with CS simulator and Kafka.
5) Test all CI/CD pipeline on this task: make sure that there are auto builds: 
5.1
after pull request to develop branch, 
5.2 after merge into develop branch, 
5.3 after merge on master branch, 
5.4 publish docker image after successful step 5.3
5.5 check that job with post rules delete containers after each step (except successful step 5.3).

**Comment by Krisilda** [comment]
@bwsw could you please check the description of the task?

**Comment by bwsw** [comment]
@Krisilda Scope of the task is too big. Includes different activities. It looks like project description.

**Comment by Krisilda** [comment]
@bwsw we can separate CI part but will it be convenient because the first part of the task need CI to be completed? 
Should we also split CI part to implement settings for each trigger?

**Comment by bwsw** [comment]
Ok, then create number of separate tasks - every should be small and include only single deliverable.

**Comment by bwsw** [comment]
@Krisilda Use scrum, plan iteration, estimate tasks, use story points. Run iteration, etc.

**Comment by Krisilda** [comment]
@bwsw I have created tasks for CI, could you please review the description of tasks which are in 'To approve' state? 

Do we need to use scrum in the project with one developer?

**Comment by bwsw** [comment]
@Krisilda yes we do
