### ISSUE TITLE
Prepare post rules for builds

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-simulator-kafka#11]
Make a plan of implementation and coordinate it with Ivan.

Common requirements:
- All progress steps should be described and should be used to make instruction on how set up CI pipeline.

Steps:

1. destroy the containers after successful or failed builds on the following triggers: pull request to develop, merge to develop. 
2.  destroy the containers after failed build on the trigger- merge to master. 
3. destroy the Image after successful build on the trigger- container publishing.
4. clean all components which were created.  
5. make a setting to clean before the build.
6. do not destroy image after a successful build on the trigger- merge to master (this image will be used for publishing).
7. do not destroy image after a failed build on the trigger- container publishing.

**Comment by MedvedevBW** [comment]
Steps:

    1. destroy the containers after successful or failed builds on the following triggers: pull request to develop, merge to develop (post build script).
    2. destroy the containers after successful or failed build on the trigger- merge to master (post build script).
    3. destroy the image after successful build on the trigger- image publishing (publish job).
    4. clean all components which were created (delete work space when build is done).
    5. make a setting to clean before the build (automatically replaced to new).
    6. do not destroy image after a successful build on the trigger - merge to master, merge to develop, pull request to develop (this image will be used for publishing).
    7. do not destroy image after a failed build on the trigger- container publishing (publish job).

**Comment by Krisilda** [comment]
@MedvedevBW please check that you also destroy images of CS simulator and Kafka for the 1st point. 
Kafka image, as well as its container, should be destroyed for the 2nd point.

**Comment by MedvedevBW** [comment]
Steps was corrected:
1. destroy the containers and images after successful or failed builds on the following triggers: pull request to develop, merge to develop, merge to master (post build script).
2. clean all components which were created (delete work space when build is done).
3. make a setting to clean before the build (automatically replaced to new).
