### ISSUE TITLE
Prepare Jenkins job for publishing docker container 

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-simulator-kafka#12]
Make a plan of implementation and coordinate it with Ivan.

Common requirements:
Make Jenkins job.
- All progress steps should be described and should be used to make instruction on how set up CI pipeline.
- Create Jenkins job
- The job should use docker image which was created by 1st job when develop branch was merged into master branch successfully. 

Steps:
- add a setting to the 1st job to run publishing job after a successful build with the trigger- merge into the master branch.  
- publish the docker image to docker hub using tags (coordinate with Ivan - using versions from version file in the repository or in docker file)

**Comment by MedvedevBW** [comment]
Job with name "publish_and_remove_docker_image" was created

**Comment by MedvedevBW** [comment]
It will be made in job for integration tests.
