### ISSUE TITLE
Make a plan for integration tests

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-simulator-kafka#13]
1) Make a plan for integration tests to check that CS simulator API is available and Kafka contains events - coordinate plan with Ivan.

**Comment by MedvedevBW** [comment]
1. Create file integration_tests.sh in project.
integration_tests.sh must be include:
a. Check availability of cloudstack with help of curl (curl --fail http://localost:8888/client/ --retry 30 --retry-delay 30)
b. Check events in the Kafka topic (Count of it must be greater than 0): test $(docker exec -it <conteiner id> ./bin/kafka-run-class.sh kafka.tools.GetOffsetShell
 --broker-list $KAFKA_HOST:  $KAFKA_PORT
 --topic $KAFKA_TOPIC --time -1 --offsets 1
 | awk -F  ":" '{sum += $3} END {print sum}') -gt 0
